---
- name: DB configuration
  hosts: webservers
  vars:
    rds_endpoint: "{{ rds_host }}" # Terraform에서 생성 후 CI/CD로 전달 받아야 함
    database_name: "{{ db_name | default('voting_db') }}"
    db_username: "{{ db_user | default('admin') }}"
    db_password: "{{ db_password }}" # 위와 같음

  tasks:
    - name: Create config directory
      file:
        path: /opt/config
        state: directory
        mode: '0755'
        owner: ec2-user
        group: ec2-user
      become: yes

    - name: Deploy application.yml
      template:
        src: ../templates/application.yaml.j2
        dest: /opt/config/application.yml
        mode: '0644'
        owner: ec2-user
        group: ec2-user
      become: yes