---
- name: Deploy JAR File
  hosts: webservers

  tasks:
    - name: Stop voting-app service
      systemd:
        name: voting-app
        state: stopped
      failed_when: false

    - name: Wait for service to stop
      wait_for:
        timeout: 10

    - name: Copy JAR file from build location
      copy:
        src: "{{ jar_source_path | default('../../backend/build/libs/') }}"
        dest: /opt/app/app.jar
        owner: ec2-user
        group: ec2-user
        mode: '0755'
      when: jar_source_path is defined

    - name: Check if JAR file exists
      stat:
        path: /opt/app/app.jar
      register: jar_file

    - name: Fail if JAR file not found
      fail:
        msg: "JAR file not found at /opt/app/app.jar. Please ensure JAR file is copied or SSM deployment completed successfully."
      when: not jar_file.stat.exists

    - name: Start voting-app service
      systemd:
        name: voting-app
        state: started
        enabled: yes
      when: jar_file.stat.exists

    - name: Verify service is running
      systemd:
        name: voting-app
      register: service_status

    - name: Show service status
      debug:
        msg: "Service status: {{ service_status.status.ActiveState }}"
