---
- name: Install Java in EC2
  hosts: webservers
  
  tasks:
    - name: Check if Java is already installed
      command: java -version
      register: java_check
      failed_when: false
    
    - name: Install JDK17 (Amazon Linux 2)
      yum:
        name: java-17-amazon-corretto-devel
        state: present
      become: yes
      when: 
        - java_check.rc != 0
        - ansible_distribution == "Amazon" and ansible_distribution_major_version == "2"
    
    - name: Install JDK17 (Amazon Linux 2023)
      dnf:
        name: java-17-amazon-corretto-devel
        state: present
      become: yes
      when: 
        - java_check.rc != 0
        - ansible_distribution == "Amazon" and ansible_distribution_major_version == "2023"
    
    - name: Verify Java installation
      command: java -version
      register: java_version
      failed_when: false
   
    - name: Show Java version
      debug:
        msg: "Java version: {{ java_version.stderr_lines[0] if java_version.stderr_lines else 'Java not found' }}"