# Spring Boot 애플리케이션 설정
spring:
  application:
    name: voting-system
  
  # JPA 및 Hibernate 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  
  # MySQL 데이터소스 설정
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:voting_db}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:admin1234}

# 서버 포트 설정
server:
  port: 8080

# 액추에이터 헬스체크 엔드포인트
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

# 로깅 설정
logging:
  level:
    org.springframework: INFO
    org.hibernate: WARN
  file:
    name: /opt/app/voting-app.log

# CORS 설정 (프론트엔드 연동용)
cors:
  allowed-origins:
    - http://localhost:3000
    - https://*.cloudfront.net
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"