# ?? ??
spring:
  application:
    name: voting-system
  
  # ?? ?? (??)
  profiles:
    active: dev

  # JPA ??
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true

  # ??? H2 ??????
  datasource:
    url: jdbc:h2:mem:voting_db
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # H2 ?? ??? (???)
  h2:
    console:
      enabled: true
      path: /h2-console

# ?? ??
server:
  port: 8080

# CORS ??
cors:
  allowed-origins:
    - http://localhost:3000
    - https://*.cloudfront.net
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"

---
# ???? ?? ?? (??? ????? ?????)
spring:
  config:
    activate:
      on-profile: prod   # ? ??? ??

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # ????? PostgreSQL (????? ??)
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/voting_db}
    username: ${DB_USERNAME:voting_user}
    password: ${DB_PASSWORD:voting_pass}
    driver-class-name: org.postgresql.Driver

  h2:
    console:
      enabled: false

server:
  port: ${SERVER_PORT:8080}
